import Head from 'next/head'
import Card from './card';

const cardList = [
  {
    title: 'Card Title 1',
    description: 'This is a description for card 1',
    image: 'https://source.unsplash.com/random/400x300',
  },
  {
    title: 'Card Title 2',
    description: 'This is a description for card 2',
    image: 'https://source.unsplash.com/random/400x300',
  },
  {
    title: 'Card Title 3',
    description: 'This is a description for card 3',
    image: 'https://source.unsplash.com/random/400x300',
  },
];

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <div className="text-3xl font-bold underline">
          Hello
        </div>
        <div className="container mx-auto py-4">
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
        {cardList.map((card, index) => (
          <Card key={index} {...card} />
        ))}
      </div>
    </div>
      </main>
      </>
    )
}
