# GitHub Actions 上での名前
name: IntervalNetlifyWebHook_09

# 起動条件
on:
  workflow_dispatch:
  schedule:
    # https://crontab.guru/#*/59_*_*_*_*
    # https://takusan.negitoro.dev/posts/github_actions/
    # https://enu23456.hatenablog.com/entry/2022/11/17/201001
    - cron: '*/59 * * * *' # 59分毎に実行

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # こっから書いていく
    steps:
      
    # NetlifyのWebHook
      - name: Netlify WebHook
        uses: wei/curl@v1.1.1
        with:
          args: -X POST -d {} ${{ secrets.WEBHOOK_URL }}
